version: '1'
services:
  mdbm2:
    image: mariadb:10.10
    container_name: mdbm2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - bridge

  nginx:
    image: nginx:1.17-alpine
    container_name: ngxm2
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose:/etc/nginx/conf.d
    networks:
      - bridge

  phpm2:
    build:
      args:
        user: david
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    image: davidmauroweb/m2storage:dev
    container_name: phpm2
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bridge
    depends_on:
      mdbm2:
        condition: service_started
        restart: true

networks:
  bridge:
    driver: bridge